/** Auto-generated by scripts/sync-zadeyo-products.mjs — do not edit by hand. */
/** Re-run: npm run sync:zadeyo */
export const ZADEYO_PRODUCT_COUNT = 165;
export const ZADEYO_MAPPED_COUNT = 166;

export const ZADEYO_PRODUCT_OVERRIDES: Record<string, string> = {
  "7-days-to-die": "7-days-to-die-cheats",
  "age-of-empires-4": "age-of-empires-4-cheats",
  "age-of-mythology-retold": "age-of-mythology-retold-cheats",
  "albion-online": "albion-online-cheats",
  "arc-raiders": "arc-raiders-cheats",
  "arena-breakout-infinite": "abi-cheats",
  "ark-survival-ascended": "ark-ascended-cheats",
  "arma-reforger": "arma-reforger-cheats",
  "armored-core-6": "armored-core-6-cheats",
  "backrooms-escape-together": "backrooms-escape-together-cheats",
  "battlebit-remastered": "battlebit-remastered-cheats",
  "battlefield-6": "BF6-cheats",
  "bellwright": "bellwright-cheats",
  "bitcraft-online": "bitcraft-online-cheats",
  "black-desert-mobile": "black-desert-online-cheats",
  "bloodline-champions": "bloodline-champions-cheats",
  "bodycam": "bodycam-cheats",
  "caliber": "caliber-novaxware-cheats",
  "call-of-duty-black-ops-7": "warzone-cheats",
  "chivalry-2": "chivalry-2-cheats",
  "chrono-odyssey": "chrono-odyssey-cheats",
  "civilization-7": "civilization-7-cheats",
  "cod-bocw": "warzone-cheats",
  "combat-master": "combat-master-cheats",
  "company-of-heroes-3": "company-of-heroes-3-cheats",
  "conan": "conan-exiles-cheats",
  "content-warning": "content-warning-cheats",
  "dark-and-darker": "dark-and-darker-cheats",
  "dauntless": "dauntless-cheats",
  "dayz": "dayz-cheats",
  "dead-by-daylight": "dbd-cheats",
  "deadside": "deadside-cheats",
  "delta-force": "delta-force-cheats",
  "demonologist": "demonologist-cheats",
  "destiny-2": "destiny-2-cheats",
  "devour": "devour-cheats",
  "dota-2": "dota-2-cheats",
  "dune-awakening": "dune-awakening-cheats",
  "ea-sports-fc": "ea-sports-fc-2026-cheats",
  "elder-scrolls-online": "elder-scrolls-online-cheats",
  "enlisted": "enlisted-cheats",
  "enshrouded": "enshrouded-cheats",
  "escape-from-tarkov": "escape-from-tarkov-cheats",
  "escape-from-tarkov-arena": "escape-from-tarkov-arena-cheats",
  "escape-the-backrooms": "escape-the-backrooms-cheats",
  "eternal-return": "eternal-return-cheats",
  "etheria-restart": "etheria-restart-novaxware-cheats",
  "exoborne": "exoborne-cheats",
  "farlight-84": "farlight-84-cheats",
  "final-fantasy-xiv": "final-fantasy-xiv-cheats",
  "forewarned": "forewarned-cheats",
  "fortnite": "fortnite-cheats",
  "foxhole": "foxhole-novaxware-cheats",
  "fragpunk": "fragpunk-novaxware-cheats",
  "genshin-impact": "genshin-impact-novaxware-cheats",
  "ghost-exile": "ghost-exile-cheats",
  "gigantic-rampage-edition": "gigantic-rampage-edition-cheats",
  "gray-zone": "gray-zone-warfare-cheats",
  "gray-zone-warfare": "gray-zone-warfare-cheats",
  "grounded": "grounded-cheats",
  "gtfo": "gtfo-cheats",
  "guild-wars-2": "guild-wars-2-cheats",
  "halo": "halo-infinite-cheats",
  "hell-let-loose": "hell-let-loose-cheats",
  "heroes-of-the-storm": "heroes-of-the-storm-cheats",
  "honkai-star-rail": "honkai-star-rail-novaxware-cheats",
  "humanitz": "humanitz-cheats",
  "hunger": "hunger-cheats",
  "hunt-showdown": "hunt-showdown-cheats",
  "icarus": "icarus-cheats",
  "inside-the-backrooms": "inside-the-backrooms-cheats",
  "insurge": "insurgency-sandstorm-cheats",
  "ironsight": "ironsight-cheats",
  "isle": "the-isle-novaxware-cheats",
  "killer-klowns-from-outer-space": "killer-klowns-from-outer-space-cheats",
  "l33t-ragemp": "fivem-cheats",
  "labyrinthine": "labyrinthine-cheats",
  "last-epoch": "last-epoch-cheats",
  "league-of-legends": "league-of-legends-cheats",
  "lethal-company": "lethal-company-cheats",
  "life-is-feudal-mmo": "life-is-feudal-mmo-cheats",
  "lost-ark": "lost-ark-cheats",
  "manor-lords": "manor-lords-cheats",
  "marauders": "marauders-cheats",
  "marvel-rivals": "marvel-rivals-cheats",
  "mecha-break": "mecha-break-cheats",
  "minecraft": "minecraft-cheats",
  "moe": "myth-of-empires-cheats",
  "monster-hunter-rise": "monster-hunter-rise-cheats",
  "monster-hunter-wilds": "monster-hunter-wilds-cheats",
  "monster-hunter-world": "monster-hunter-world-cheats",
  "mordhau": "mordhau-cheats",
  "mortal-kombat-1": "mortal-kombat-1-cheats",
  "mortal-online-2": "mortal-online-2-cheats",
  "murky-divers": "murky-divers-cheats",
  "naraka-bladepoint": "naraka-bladepoint-novaxware-cheats",
  "nba-2k26": "nba-2k26-cheats",
  "new-world": "new-world-cheats",
  "nhl-26": "nhl-26-cheats",
  "no-more-room-in-hell-2": "no-more-room-in-hell-2-cheats",
  "northgard": "northgard-cheats",
  "once-human": "once-human-cheats",
  "operation-harsh-doorstop": "operation-harsh-doorstop-cheats",
  "overwatch-2": "overwatch-2-cheats",
  "pacify": "pacify-cheats",
  "paladins": "paladins-cheats",
  "palia": "palia-cheats",
  "palworld": "palworld-cheats",
  "path-of-exile-2": "path-of-exile-cheats",
  "payday-3": "payday-3-novaxware-cheats",
  "phasmophobia": "phasmophobia-cheats",
  "planetside-2": "planetside-2-cheats",
  "pragmata": "pragmata-cheats",
  "predecessor": "predecessor-cheats",
  "project-zomboid": "project-zomboid-cheats",
  "pubg": "pubg-cheats",
  "raft": "raft-cheats",
  "rainbow-six-siege": "rainbow-six-siege-cheats",
  "ready-or-not": "ready-or-not-cheats",
  "red-dead-redemption": "red-dead-redemption-cheats",
  "redm": "redm-rp-cheats",
  "rust": "rust-cheats",
  "sa-mp": "gta5-cheats",
  "sand": "sand-raiders-of-sophie-cheats",
  "scum": "scum-cheats",
  "sea-of-thieves": "sea-of-thieves-cheats",
  "shatterline": "shatterline-cheats",
  "skin-changer": "skin-changer-cheats",
  "smite-2": "smite-2-cheats",
  "sons-of-the-forest": "sons-of-the-forest-cheats",
  "soulmask": "soulmask-cheats",
  "splitgate-2": "splitgate-2-cheats",
  "squad": "squad-cheats",
  "star-wars-zero-company": "star-wars-zero-company-cheats",
  "state-of-decay-2": "state-of-decay-2-cheats",
  "stormgate": "stormgate-cheats",
  "street-fighter-6": "street-fighter-6-cheats",
  "supervive": "supervive-cheats",
  "swbf": "star-wars-battlefront-2-cheats",
  "team-fortress-2": "team-fortress-2-cheats",
  "tekken-8": "tekken-8-cheats",
  "temtem": "temtem-cheats",
  "texas-chain-saw-massacre": "texas-chain-saw-massacre-cheats",
  "the-finals": "thefinals-cheats",
  "the-first-descendant": "the-first-descendant-cheats",
  "the-front": "the-front-novaxware-cheats",
  "the-outlast-trials": "the-outlast-trials-cheats",
  "throne-and-liberty": "throne-and-liberty-cheats",
  "torchlight-infinite": "torchlight-infinite-cheats",
  "ugc": "ugc-cheats",
  "unturned": "unturned-novaxware-cheats",
  "v-rising": "v-rising-cheats",
  "valheim": "valheim-cheats",
  "valorant": "valorant-cheats",
  "vindictus-defying-fate": "vindictus-defying-fate-cheats",
  "vintage-story": "vintage-story-cheats",
  "war-selection": "war-selection-cheats",
  "warframe": "warframe-cheats",
  "world-of-warcraft": "world-of-warcraft-cheats",
  "world-war-3": "world-war-3-cheats",
  "wows": "war-thunder-cheats",
  "wunthering": "wuthering-waves-cheats",
  "warzone": "warzone-cheats",
  "xdefiant": "xdefiant-cheats",
  "zenless-zone-zero": "zenless-zone-zero-cheats",
};

export const ZADEYO_AVAILABLE_SLUGS = new Set<string>([
  "7-days-to-die",
  "age-of-empires-4",
  "age-of-mythology-retold",
  "albion-online",
  "arc-raiders",
  "arena-breakout-infinite",
  "ark-survival-ascended",
  "arma-reforger",
  "armored-core-6",
  "backrooms-escape-together",
  "battlebit-remastered",
  "battlefield-6",
  "bellwright",
  "bitcraft-online",
  "black-desert-mobile",
  "bloodline-champions",
  "bodycam",
  "caliber",
  "call-of-duty-black-ops-7",
  "chivalry-2",
  "chrono-odyssey",
  "civilization-7",
  "cloud-dma",
  "cod-bocw",
  "combat-master",
  "company-of-heroes-3",
  "conan",
  "content-warning",
  "dark-and-darker",
  "dauntless",
  "dayz",
  "dead-by-daylight",
  "deadside",
  "delta-force",
  "demonologist",
  "destiny-2",
  "devour",
  "dota-2",
  "dune-awakening",
  "ea-sports-fc",
  "elder-scrolls-online",
  "enlisted",
  "enshrouded",
  "escape-from-tarkov",
  "escape-from-tarkov-arena",
  "escape-the-backrooms",
  "eternal-return",
  "etheria-restart",
  "exoborne",
  "farlight-84",
  "final-fantasy-xiv",
  "forewarned",
  "fortnite",
  "foxhole",
  "fragpunk",
  "genshin-impact",
  "ghost-exile",
  "gigantic-rampage-edition",
  "gray-zone",
  "gray-zone-warfare",
  "grounded",
  "gtfo",
  "guild-wars-2",
  "halo",
  "hell-let-loose",
  "heroes-of-the-storm",
  "honkai-star-rail",
  "humanitz",
  "hunger",
  "hunt-showdown",
  "hwid-spoofer",
  "icarus",
  "inside-the-backrooms",
  "insurge",
  "ironsight",
  "isle",
  "killer-klowns-from-outer-space",
  "l33t-ragemp",
  "labyrinthine",
  "last-epoch",
  "league-of-legends",
  "lethal-company",
  "life-is-feudal-mmo",
  "lost-ark",
  "manor-lords",
  "marauders",
  "marvel-rivals",
  "mecha-break",
  "minecraft",
  "moe",
  "monster-hunter-rise",
  "monster-hunter-wilds",
  "monster-hunter-world",
  "mordhau",
  "mortal-kombat-1",
  "mortal-online-2",
  "murky-divers",
  "naraka-bladepoint",
  "nba-2k26",
  "new-world",
  "nhl-26",
  "no-more-room-in-hell-2",
  "northgard",
  "once-human",
  "operation-harsh-doorstop",
  "overwatch-2",
  "pacify",
  "paladins",
  "palia",
  "palworld",
  "path-of-exile-2",
  "payday-3",
  "phasmophobia",
  "planetside-2",
  "pragmata",
  "predecessor",
  "project-zomboid",
  "pubg",
  "raft",
  "rainbow-six-siege",
  "ready-or-not",
  "red-dead-redemption",
  "redm",
  "rust",
  "sa-mp",
  "sand",
  "scum",
  "sea-of-thieves",
  "shatterline",
  "skin-changer",
  "smite-2",
  "sons-of-the-forest",
  "soulmask",
  "splitgate-2",
  "squad",
  "star-wars-zero-company",
  "state-of-decay-2",
  "stormgate",
  "street-fighter-6",
  "supervive",
  "swbf",
  "team-fortress-2",
  "tekken-8",
  "temtem",
  "texas-chain-saw-massacre",
  "the-finals",
  "the-first-descendant",
  "the-front",
  "the-outlast-trials",
  "throne-and-liberty",
  "torchlight-infinite",
  "ugc",
  "unturned",
  "v-rising",
  "valheim",
  "valorant",
  "vindictus-defying-fate",
  "vintage-story",
  "war-selection",
  "warframe",
  "warzone",
  "world-of-warcraft",
  "world-war-3",
  "wows",
  "wunthering",
  "xdefiant",
  "zenless-zone-zero",
]);

export type ZadeyoMapping = {
  catalogSlug: string;
  title: string;
  zadeyoSlug: string;
  match: string;
};

export const ZADEYO_MAPPINGS: ZadeyoMapping[] = [
  {
    "catalogSlug": "escape-from-tarkov",
    "title": "Escape from Tarkov",
    "zadeyoSlug": "escape-from-tarkov-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "rust",
    "title": "RUST",
    "zadeyoSlug": "rust-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "dayz",
    "title": "DayZ",
    "zadeyoSlug": "dayz-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "pubg",
    "title": "PUBG",
    "zadeyoSlug": "pubg-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "battlefield-6",
    "title": "Battlefield 6",
    "zadeyoSlug": "BF6-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "call-of-duty-black-ops-7",
    "title": "Call of Duty: Black Ops 7",
    "zadeyoSlug": "warzone-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "team-fortress-2",
    "title": "Team Fortress 2",
    "zadeyoSlug": "team-fortress-2-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "company-of-heroes-3",
    "title": "Company of Heroes 3",
    "zadeyoSlug": "company-of-heroes-3-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "7-days-to-die",
    "title": "7 Days to Die",
    "zadeyoSlug": "7-days-to-die-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "humanitz",
    "title": "HumanitZ",
    "zadeyoSlug": "humanitz-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "ark-survival-ascended",
    "title": "ARK: Survival Ascended",
    "zadeyoSlug": "ark-ascended-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "mecha-break",
    "title": "Mecha BREAK",
    "zadeyoSlug": "mecha-break-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "sand",
    "title": "SAND",
    "zadeyoSlug": "sand-raiders-of-sophie-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "cod-bocw",
    "title": "Cod Bocw",
    "zadeyoSlug": "warzone-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "swbf",
    "title": "Swbf",
    "zadeyoSlug": "star-wars-battlefront-2-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "wows",
    "title": "Wows",
    "zadeyoSlug": "war-thunder-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "halo",
    "title": "Halo",
    "zadeyoSlug": "halo-infinite-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "insurge",
    "title": "Insurge",
    "zadeyoSlug": "insurgency-sandstorm-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "moe",
    "title": "Moe",
    "zadeyoSlug": "myth-of-empires-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "isle",
    "title": "Isle",
    "zadeyoSlug": "the-isle-novaxware-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "conan",
    "title": "Conan",
    "zadeyoSlug": "conan-exiles-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "wunthering",
    "title": "Wunthering",
    "zadeyoSlug": "wuthering-waves-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "gray-zone",
    "title": "Gray Zone",
    "zadeyoSlug": "gray-zone-warfare-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "gray-zone-warfare",
    "title": "Gray Zone Warfare",
    "zadeyoSlug": "gray-zone-warfare-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "bodycam",
    "title": "Bodycam",
    "zadeyoSlug": "bodycam-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "once-human",
    "title": "Once Human",
    "zadeyoSlug": "once-human-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "l33t-ragemp",
    "title": "L33T RageMP",
    "zadeyoSlug": "fivem-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "predecessor",
    "title": "Predecessor",
    "zadeyoSlug": "predecessor-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "the-first-descendant",
    "title": "The First Descendant",
    "zadeyoSlug": "the-first-descendant-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "zenless-zone-zero",
    "title": "Zenless Zone Zero",
    "zadeyoSlug": "zenless-zone-zero-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "sa-mp",
    "title": "SA-MP",
    "zadeyoSlug": "gta5-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "black-desert-mobile",
    "title": "Black Desert Mobile",
    "zadeyoSlug": "black-desert-online-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "ea-sports-fc",
    "title": "EA Sports FC",
    "zadeyoSlug": "ea-sports-fc-2026-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "marvel-rivals",
    "title": "Marvel Rivals",
    "zadeyoSlug": "marvel-rivals-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "arma-reforger",
    "title": "Arma Reforger",
    "zadeyoSlug": "arma-reforger-cheats",
    "match": "exact-cheats"
  },
  {
    "catalogSlug": "fragpunk",
    "title": "FragPunk",
    "zadeyoSlug": "fragpunk-novaxware-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "path-of-exile-2",
    "title": "Path of Exile 2",
    "zadeyoSlug": "path-of-exile-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "last-epoch",
    "title": "Last Epoch",
    "zadeyoSlug": "last-epoch-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "arc-raiders",
    "title": "ARC Raiders",
    "zadeyoSlug": "arc-raiders-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "etheria-restart",
    "title": "Etheria Restart",
    "zadeyoSlug": "etheria-restart-novaxware-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "foxhole",
    "title": "Foxhole",
    "zadeyoSlug": "foxhole-novaxware-cheats",
    "match": "manual"
  },
  {
    "catalogSlug": "age-of-empires-4",
    "title": "Age of Empires IV",
    "zadeyoSlug": "age-of-empires-4-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "age-of-mythology-retold",
    "title": "Age of Mythology Retold",
    "zadeyoSlug": "age-of-mythology-retold-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "albion-online",
    "title": "Albion Online",
    "zadeyoSlug": "albion-online-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "arena-breakout-infinite",
    "title": "ARENA BREAKOUT",
    "zadeyoSlug": "abi-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "armored-core-6",
    "title": "Armored Core VI",
    "zadeyoSlug": "armored-core-6-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "backrooms-escape-together",
    "title": "Backrooms: Escape Together",
    "zadeyoSlug": "backrooms-escape-together-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "battlebit-remastered",
    "title": "BattleBit Remastered",
    "zadeyoSlug": "battlebit-remastered-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "bellwright",
    "title": "Bellwright",
    "zadeyoSlug": "bellwright-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "bitcraft-online",
    "title": "BitCraft Online",
    "zadeyoSlug": "bitcraft-online-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "bloodline-champions",
    "title": "Bloodline Champions",
    "zadeyoSlug": "bloodline-champions-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "caliber",
    "title": "CALIBER",
    "zadeyoSlug": "caliber-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "chivalry-2",
    "title": "Chivalry 2",
    "zadeyoSlug": "chivalry-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "chrono-odyssey",
    "title": "Chrono Odyssey",
    "zadeyoSlug": "chrono-odyssey-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "civilization-7",
    "title": "Civilization VII",
    "zadeyoSlug": "civilization-7-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "cloud-dma",
    "title": "CLOUD DMA",
    "zadeyoSlug": "cloud-dma",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "combat-master",
    "title": "Combat Master",
    "zadeyoSlug": "combat-master-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "content-warning",
    "title": "Content Warning",
    "zadeyoSlug": "content-warning-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "dark-and-darker",
    "title": "Dark and Darker",
    "zadeyoSlug": "dark-and-darker-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "dauntless",
    "title": "Dauntless",
    "zadeyoSlug": "dauntless-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "dead-by-daylight",
    "title": "DEAD BY DAYLIGHT",
    "zadeyoSlug": "dbd-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "deadside",
    "title": "Deadside",
    "zadeyoSlug": "deadside-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "delta-force",
    "title": "DELTA FORCE",
    "zadeyoSlug": "delta-force-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "demonologist",
    "title": "Demonologist",
    "zadeyoSlug": "demonologist-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "destiny-2",
    "title": "Destiny 2",
    "zadeyoSlug": "destiny-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "devour",
    "title": "Devour",
    "zadeyoSlug": "devour-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "dota-2",
    "title": "DOTA 2",
    "zadeyoSlug": "dota-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "dune-awakening",
    "title": "DUNE AWAKENING",
    "zadeyoSlug": "dune-awakening-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "enlisted",
    "title": "Enlisted",
    "zadeyoSlug": "enlisted-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "enshrouded",
    "title": "Enshrouded",
    "zadeyoSlug": "enshrouded-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "escape-from-tarkov-arena",
    "title": "Escape from Tarkov: Arena",
    "zadeyoSlug": "escape-from-tarkov-arena-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "escape-the-backrooms",
    "title": "Escape the Backrooms",
    "zadeyoSlug": "escape-the-backrooms-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "eternal-return",
    "title": "Eternal Return",
    "zadeyoSlug": "eternal-return-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "exoborne",
    "title": "Exoborne",
    "zadeyoSlug": "exoborne-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "farlight-84",
    "title": "Farlight 84",
    "zadeyoSlug": "farlight-84-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "final-fantasy-xiv",
    "title": "Final Fantasy XIV",
    "zadeyoSlug": "final-fantasy-xiv-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "forewarned",
    "title": "Forewarned",
    "zadeyoSlug": "forewarned-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "fortnite",
    "title": "FORTNITE",
    "zadeyoSlug": "fortnite-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "genshin-impact",
    "title": "GENSHIN IMPACT",
    "zadeyoSlug": "genshin-impact-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "ghost-exile",
    "title": "Ghost Exile",
    "zadeyoSlug": "ghost-exile-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "gigantic-rampage-edition",
    "title": "Gigantic: Rampage Edition",
    "zadeyoSlug": "gigantic-rampage-edition-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "grounded",
    "title": "Grounded",
    "zadeyoSlug": "grounded-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "gtfo",
    "title": "GTFO",
    "zadeyoSlug": "gtfo-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "guild-wars-2",
    "title": "Guild Wars 2",
    "zadeyoSlug": "guild-wars-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "hell-let-loose",
    "title": "Hell Let Loose",
    "zadeyoSlug": "hell-let-loose-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "heroes-of-the-storm",
    "title": "Heroes of the Storm",
    "zadeyoSlug": "heroes-of-the-storm-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "honkai-star-rail",
    "title": "HONKAI STAR RAIL",
    "zadeyoSlug": "honkai-star-rail-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "hunger",
    "title": "HUNGER HUNGER",
    "zadeyoSlug": "hunger-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "hunt-showdown",
    "title": "Hunt: Showdown",
    "zadeyoSlug": "hunt-showdown-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "hwid-spoofer",
    "title": "HWID SPOOFER",
    "zadeyoSlug": "hwid-spoofer",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "icarus",
    "title": "Icarus",
    "zadeyoSlug": "icarus-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "inside-the-backrooms",
    "title": "Inside the Backrooms",
    "zadeyoSlug": "inside-the-backrooms-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "ironsight",
    "title": "Ironsight",
    "zadeyoSlug": "ironsight-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "killer-klowns-from-outer-space",
    "title": "Killer Klowns From Outer Space: The Game",
    "zadeyoSlug": "killer-klowns-from-outer-space-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "labyrinthine",
    "title": "Labyrinthine",
    "zadeyoSlug": "labyrinthine-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "league-of-legends",
    "title": "League of legends",
    "zadeyoSlug": "league-of-legends-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "lethal-company",
    "title": "Lethal Company",
    "zadeyoSlug": "lethal-company-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "life-is-feudal-mmo",
    "title": "Life is Feudal MMO",
    "zadeyoSlug": "life-is-feudal-mmo-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "lost-ark",
    "title": "Lost Ark",
    "zadeyoSlug": "lost-ark-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "manor-lords",
    "title": "Manor Lords",
    "zadeyoSlug": "manor-lords-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "marauders",
    "title": "Marauders",
    "zadeyoSlug": "marauders-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "minecraft",
    "title": "MINECRAFT",
    "zadeyoSlug": "minecraft-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "monster-hunter-rise",
    "title": "Monster Hunter Rise",
    "zadeyoSlug": "monster-hunter-rise-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "monster-hunter-wilds",
    "title": "Monster Hunter Wilds",
    "zadeyoSlug": "monster-hunter-wilds-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "monster-hunter-world",
    "title": "Monster Hunter World",
    "zadeyoSlug": "monster-hunter-world-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "mordhau",
    "title": "Mordhau",
    "zadeyoSlug": "mordhau-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "mortal-kombat-1",
    "title": "Mortal Kombat 1",
    "zadeyoSlug": "mortal-kombat-1-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "mortal-online-2",
    "title": "Mortal Online 2",
    "zadeyoSlug": "mortal-online-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "murky-divers",
    "title": "Murky Divers",
    "zadeyoSlug": "murky-divers-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "naraka-bladepoint",
    "title": "NARAKA BLADEPOINT",
    "zadeyoSlug": "naraka-bladepoint-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "nba-2k26",
    "title": "NBA 2K26",
    "zadeyoSlug": "nba-2k26-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "new-world",
    "title": "New World",
    "zadeyoSlug": "new-world-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "nhl-26",
    "title": "NHL 26",
    "zadeyoSlug": "nhl-26-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "no-more-room-in-hell-2",
    "title": "No More Room in Hell 2",
    "zadeyoSlug": "no-more-room-in-hell-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "northgard",
    "title": "Northgard",
    "zadeyoSlug": "northgard-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "operation-harsh-doorstop",
    "title": "Operation Harsh Doorstop",
    "zadeyoSlug": "operation-harsh-doorstop-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "overwatch-2",
    "title": "OVERWATCH 2",
    "zadeyoSlug": "overwatch-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "pacify",
    "title": "Pacify",
    "zadeyoSlug": "pacify-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "paladins",
    "title": "PALADINS",
    "zadeyoSlug": "paladins-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "palia",
    "title": "Palia",
    "zadeyoSlug": "palia-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "palworld",
    "title": "Palworld",
    "zadeyoSlug": "palworld-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "payday-3",
    "title": "PAYDAY 3",
    "zadeyoSlug": "payday-3-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "phasmophobia",
    "title": "Phasmophobia",
    "zadeyoSlug": "phasmophobia-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "planetside-2",
    "title": "PlanetSide 2",
    "zadeyoSlug": "planetside-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "pragmata",
    "title": "pragmata",
    "zadeyoSlug": "pragmata-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "project-zomboid",
    "title": "Project Zomboid",
    "zadeyoSlug": "project-zomboid-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "raft",
    "title": "Raft",
    "zadeyoSlug": "raft-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "rainbow-six-siege",
    "title": "RAINBOW SIX SIEGE",
    "zadeyoSlug": "rainbow-six-siege-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "ready-or-not",
    "title": "Ready or Not",
    "zadeyoSlug": "ready-or-not-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "red-dead-redemption",
    "title": "RED DEAD REDEMPTION",
    "zadeyoSlug": "red-dead-redemption-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "redm",
    "title": "RedM RP",
    "zadeyoSlug": "redm-rp-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "scum",
    "title": "SCUM",
    "zadeyoSlug": "scum-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "sea-of-thieves",
    "title": "Sea of Thieves",
    "zadeyoSlug": "sea-of-thieves-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "shatterline",
    "title": "Shatterline",
    "zadeyoSlug": "shatterline-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "skin-changer",
    "title": "Skin Changer",
    "zadeyoSlug": "skin-changer-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "smite-2",
    "title": "SMITE 2",
    "zadeyoSlug": "smite-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "sons-of-the-forest",
    "title": "Sons of the Forest",
    "zadeyoSlug": "sons-of-the-forest-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "soulmask",
    "title": "Soulmask",
    "zadeyoSlug": "soulmask-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "splitgate-2",
    "title": "Splitgate 2",
    "zadeyoSlug": "splitgate-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "squad",
    "title": "SQUAD",
    "zadeyoSlug": "squad-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "star-wars-zero-company",
    "title": "STAR WARS Zero Company™",
    "zadeyoSlug": "star-wars-zero-company-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "state-of-decay-2",
    "title": "State of Decay 2",
    "zadeyoSlug": "state-of-decay-2-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "stormgate",
    "title": "Stormgate",
    "zadeyoSlug": "stormgate-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "street-fighter-6",
    "title": "Street Fighter 6",
    "zadeyoSlug": "street-fighter-6-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "supervive",
    "title": "Supervive",
    "zadeyoSlug": "supervive-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "tekken-8",
    "title": "Tekken 8",
    "zadeyoSlug": "tekken-8-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "temtem",
    "title": "Temtem",
    "zadeyoSlug": "temtem-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "texas-chain-saw-massacre",
    "title": "Texas Chain Saw Massacre",
    "zadeyoSlug": "texas-chain-saw-massacre-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "elder-scrolls-online",
    "title": "The Elder Scrolls Online",
    "zadeyoSlug": "elder-scrolls-online-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "the-front",
    "title": "THE FRONT",
    "zadeyoSlug": "the-front-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "the-outlast-trials",
    "title": "The Outlast Trials",
    "zadeyoSlug": "the-outlast-trials-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "the-finals",
    "title": "THEFINALS",
    "zadeyoSlug": "thefinals-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "throne-and-liberty",
    "title": "Throne and Liberty",
    "zadeyoSlug": "throne-and-liberty-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "torchlight-infinite",
    "title": "Torchlight Infinite",
    "zadeyoSlug": "torchlight-infinite-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "ugc",
    "title": "UGC",
    "zadeyoSlug": "ugc-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "unturned",
    "title": "UNTURNED",
    "zadeyoSlug": "unturned-novaxware-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "v-rising",
    "title": "V Rising",
    "zadeyoSlug": "v-rising-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "valheim",
    "title": "Valheim",
    "zadeyoSlug": "valheim-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "valorant",
    "title": "VALORANT",
    "zadeyoSlug": "valorant-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "vindictus-defying-fate",
    "title": "Vindictus: Defying Fate",
    "zadeyoSlug": "vindictus-defying-fate-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "vintage-story",
    "title": "Vintage Story",
    "zadeyoSlug": "vintage-story-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "war-selection",
    "title": "War Selection",
    "zadeyoSlug": "war-selection-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "warframe",
    "title": "Warframe",
    "zadeyoSlug": "warframe-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "world-of-warcraft",
    "title": "World of Warcraft",
    "zadeyoSlug": "world-of-warcraft-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "world-war-3",
    "title": "WORLD WAR 3",
    "zadeyoSlug": "world-war-3-cheats",
    "match": "extra-catalog"
  },
  {
    "catalogSlug": "xdefiant",
    "title": "XDefiant",
    "zadeyoSlug": "xdefiant-cheats",
    "match": "extra-catalog"
  }
] as ZadeyoMapping[];

/** Zadeyo products not yet in our catalog (1 items). */
export const ZADEYO_UNMAPPED_PRODUCTS: string[] = [
  "meccha-chameleon-cheats"
];
